name: lb2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - freetype
  - libpng
  - python=3.10.15
  - pytorch=2.5.0
  - pip
  - pip:
    - -r team_code/requirements.txt