name: garage
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - freetype
  - libpng
  - python=3.7
  - pip
  - pip:
    - -r team_code/requirements.txt
    - carla==0.9.14
    - webcolors
    - -r /cluster/work/andrebw/carla_garage/leaderboard/requirements.txt
    - -r /cluster/work/andrebw/carla_garage/scenario_runner/requirements.txt